"""altered tables

Revision ID: 79ed574cc2d7
Revises: 1bfcb7de8001
Create Date: 2026-05-29 17:27:58.254725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79ed574cc2d7'
down_revision: Union[str, Sequence[str], None] = '1bfcb7de8001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_timestamp'), table_name='api_logs')
    op.drop_index(op.f('idx_username'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('idx_category'), table_name='sales')
    op.drop_index(op.f('idx_product_name'), table_name='sales')
    op.drop_index(op.f('idx_region'), table_name='sales')
    op.drop_index(op.f('idx_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_category'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_name'), table_name='sales')
    op.drop_index(op.f('ix_sales_region'), table_name='sales')
    op.drop_index(op.f('ix_sales_sales_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_forecast_date'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_forecast_date'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_forecast_history_id'), table_name='forecast_history')
    op.drop_table('forecast_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('predicted_demand', mysql.FLOAT(), nullable=True),
    sa.Column('model_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('generated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('generated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_history_id'), 'forecast_history', ['id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', sa.DATE(), nullable=True),
    sa.Column('predicted_demand', mysql.FLOAT(), nullable=True),
    sa.Column('sales_trend', mysql.FLOAT(), nullable=True),
    sa.Column('weekly_pattern', mysql.FLOAT(), nullable=True),
    sa.Column('yearly_pattern', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_results_forecast_date'), 'forecast_results', ['forecast_date'], unique=False)
    op.create_index(op.f('idx_forecast_date'), 'forecast_results', ['forecast_date'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.create_table('model_metadata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_trained_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_sales_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sales_date', sa.DATE(), nullable=True),
    sa.Column('quantity_sold', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenue', mysql.FLOAT(), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('stock_available', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sales_sales_date'), 'sales', ['sales_date'], unique=False)
    op.create_index(op.f('ix_sales_region'), 'sales', ['region'], unique=False)
    op.create_index(op.f('ix_sales_product_name'), 'sales', ['product_name'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_category'), 'sales', ['category'], unique=False)
    op.create_index(op.f('idx_sales_date'), 'sales', ['sales_date'], unique=False)
    op.create_index(op.f('idx_region'), 'sales', ['region'], unique=False)
    op.create_index(op.f('idx_product_name'), 'sales', ['product_name'], unique=False)
    op.create_index(op.f('idx_category'), 'sales', ['category'], unique=False)
    op.create_table('reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('generated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('api_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('endpoint', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('method', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_api_logs_id'), 'api_logs', ['id'], unique=False)
    op.create_index(op.f('idx_username'), 'api_logs', ['username'], unique=False)
    op.create_index(op.f('idx_timestamp'), 'api_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###
